/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false` (hash: 6833f452602d7a5578615d1f29345737)
interface __BaseEnv_Env {
	MAIL_STORE: R2Bucket;
	DB: D1Database;
	EMAIL: SendEmail;
	ASSETS: Fetcher;
	ACCOUNT_ID: "";
	ACCESS_TEAM_DOMAIN: "https://your-team.cloudflareaccess.com";
	ACCESS_AUD: "";
	APP_ORIGIN: "https://mail.example.com";
	MCP_HOST: "mcp.mail.example.com";
	EMAIL_WORKER_NAME: "mail-hq";
	REDIRECT_HOSTS: "";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/src/entry");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ACCOUNT_ID" | "ACCESS_TEAM_DOMAIN" | "ACCESS_AUD" | "APP_ORIGIN" | "MCP_HOST" | "EMAIL_WORKER_NAME" | "REDIRECT_HOSTS">> {}
}
